version: '2'

services:
    server:
        build: ./
        image: greenhr_server
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ".:/app"
        links:
            - db
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - "./store:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=greenHR
            - POSTGRES_PASSWORD=RHneerg
            - POSTGRES_DB=greenHRDB